version: "3.8"
services:
  db:
    image: postgres:latest
    ports:
      - "5438:5432"
    container_name: spring_aop
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=spring_aop