server:
  port: 8080

spring:
  application:
    name: project
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5439/db_spring # This is used first, since it's earlier
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: t1-intensive

